Users:
  create_user:
    url: /api/v1/users
    method: POST

  get_users:
    url: /api/v1/users
    method: GET

  get_user:
    url: /api/v1/users/:id
    method: POST

  update_user:
    url: /api/v1/users/:id
    method: PUT

  remove_user:
    url: /api/v1/users/:id
    method: DELETE

Products:
  get_products:
    url: /api/v1/products?tag=tag_name&discount=boolean
    method: GET

  get_product:
    url: /api/v1/products/:id
    method: GET

Admin:
  create_product:
    url: /api/v1/admin/products
    method: POST

  update_product:
    url: /api/v1/admin/products/:id
    method: PUT

  remove_product:
    url: /api/v1/admin/products/:id
    method: DELETE

  get_orders:
    url: /api/v1/admin/orders
    method: GET

  get_order:
    url: /api/v1/admin/orders/:id
    method: GET

  complete_order:
    url: /api/v1/admin/orders/:id
    method: POST

  remove_order:
    url: /api/v1/admin/orders/:id
    method: DELETE

Cart:
  create_cart:
    url: /api/v1/cart
    method: POST

  update_cart_product:
    url: /api/v1/cart/:id/product
    method: POST

  remove_cart_product:
    url: /api/v1/cart/:id/product
    method: DELETE

  remove_cart:
    url: /api/v1/cart/:id
    method: DELETE

  get_cart:
    url: /api/v1/cart/:id
    method: GET

BuyProduct:
  checkout:
    url: /api/v1/checkout
    method: POST

  payment:
    url: /api/v1/payment
    method: POST
